### ISSUE TITLE
agherant_standalone ignore environment configurations

### ISSUE THREAD

**Issue by ael-code** [insomnia-lab/libreant#81] opened 2015-02-04 17:01 UTC
The problem is about a bug in agherant_standalone module initialization.
AppConfig use the flask app name as prefix of environment configuration names.
We initialize Flask app on agherant_standalone using classic ```Flask(__name__)``` call, but in this case ```__name__``` is equal to ```WEBANT.AGHERANT_STANDALONE```.
The result is that all the environment configurations prefixed with WEBANT are ignored.

To reproduce the problem, ensure that your db contains some elements and launch ```WEBANT_AGHERANT_DESCRIPTIONS='["SELF"]' agherant```. If you search with query ```*:*``` you will find that no results will be shown.

**Comment by boyska** [comment] 2015-02-04 17:09
I have checked that just replacing `webant` in place of `__name__`

**Comment by ael-code** [comment] 2015-02-04 17:11
This app is going to became bigger and bigger and I think we should reorganize configuration handling.

Every module should have its own prefix. For example webant configurations should start with ```WEBANT```, agherant with ```AGHERANT``` and so on...

I don't think that AppConfig extension provides this possibility.
We can prefix all config with ```LIBREANT``` and then use sub prefix to specialize config.

**Comment by ael-code** [comment] 2015-02-04 17:14
> I have checked that just replacing webant in place of __name__

maybe I'am missing something but if I apply the patch you provided when I search in agherant I encounter in:
```
jinja2.exceptions.TemplateNotFound: 
TemplateNotFound: os_search.html
```

**Comment by boyska** [comment] 2015-02-04 17:58
ok maybe I havent' checked good enough :)

I agree to be more explicit about configuration, without relying on `app.name`, as AppConfig is doing. We should choose a prefix and stick with it, without this messing where is flask looking for templates.

But I am not so sure about having each module with its own prefix. It could be meaningful for agherant, but I don't see many other cases (and many other modules, actually).
So, is the fsdb path something like `LIBREANT_FSDB_PATH`? or is it a module on his own? And what about debug?
I am quite happy about the "one single config namespace, but decent conventions about prefixes" approach. It's simple, not overengineered, works well.
I mean, if a module really needs to read a variable from another module, it should be able to do it. Yes, it would probably be ugly, but that's another part.
Usually isolating config is about security, but in our case it is not: the process space is the same, so there's no variable that is really "obscure" to other modules, if they are wicked.

**Comment by ael-code** [comment] 2015-02-04 23:19
So ```LIBREANT``` as prefix and sub_prefix with module name?

 - ```LIBREANT_WEBANT```
 - ```LIBREANT_AGHERANT```
 
and to keep things simple I will put fsdb_path config file under webant prefix:

 - ```LIBREANT_WEBANT_FSDB_PATH```

**Comment by boyska** [comment] 2015-02-05 12:51
Conceptually, `FSDB_PATH` is not related to web. Yes, I know that I started the confusion creating a `webant` module that is not just web-specific. But we can keep options sane nevertheless.

I'd do with more "conceptual" names, without much regard of the code organization.
For example `LIBREANT_HTTP_PORT` or `LIBREANT_HTTP_SOMEWEBSPECIFICOPTION`. Things that are part of just libreant, like elasticsearch configuration, could go for example in LIBREANT_ES_DB_URI, then LIBREANT_USERDB_URI for the auth user (ok, when we'll have one) or LIBREANT_USERDB_SYNC if we for example decide to support the sync option on the db. LIBREANT_AGHERANT_ seems ok as a prefix for its own options.

**Comment by ael-code** [comment] 2015-02-06 13:50
oke

**Comment by boyska** [comment] 2015-02-06 14:15
Ok, so, in another project I have, I had to do some configuration handling, and I just stole code from appconfig, behaving like this.
* hardcoding a prefix
* read every option starting with that prefix as in json
* read `${prefix}_CONFIG` assuming it is a json file

This is just the same thing that AppConfig does, BUT AppConfig forces prefix to be something related to `app.name` (that is, `__name__`).

**Comment by ael-code** [comment] 2015-02-06 14:17
nice.
Where are you going to put the code? I think this is not webant related

**Comment by boyska** [comment] 2015-02-06 14:21
I believe that if we rename the folder from `webant` to `libreant` we'd solve lot of phylosophycal doubts :)
Anyway I believe that a `config_utils` module is ok inside of whatever package, without creating one more just for this.

**Comment by ael-code** [comment] 2015-02-13 15:57
this is fixed but we said that we want to move to ```LIBREANT``` config prefix, isn't?

**Comment by boyska** [comment] 2015-02-13 16:15
On Fri, Feb 13, 2015 at 07:57:33AM -0800, ael wrote:
>this is fixed but we said that we want to move to ```LIBREANT``` config prefix, isn't?

we did. but that one is not a bug, and surely has lower priority.

IF we just want to change the prefix, then it is a one-line fix, and we
can avoid creating a new issue, and all the fuss about it.
If, instead, we want to also reorganize options, maybe closing this and
opening a new one is a better choice.

-- 
boyska

**Comment by ael-code** [comment] 2015-02-13 16:19
> If, instead, we want to also reorganize options, maybe closing this and opening a new one is a better choice.

I prefer the hard way.

**Comment by boyska** [comment] 2015-02-13 16:35
ok, so this should be closed, and a new one should be opened, am I correct? can _you_ do that?

**Comment by ael-code** [comment] 2015-02-13 16:44
Yes, but not right now.

**Comment by boyska** [comment] 2015-02-13 16:46
ok. I believe I could just close this anyway, but I'll wait till you have more time to give an opinion on this.

**Closed** 2015-03-20 12:04 UTC
Labels: agherant, bug
